/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import DAO.ClassesDB.Passagem;
import DAO.ClassesDB.Status;
import DAO.ClassesDB.Voo;
import DAO.ClassesDB.VooPoltrona;
import DAO.SelectDAO;
import Utilidades.Facade;
import Utilidades.FormUtils;
import Utilidades.GerarDados;
import Utilidades.VooTableModel;
import java.awt.HeadlessException;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class formCompraPassagem extends javax.swing.JFrame {
    private FormUtils formUtils;
    private Voo voo;
    private VooTableModel model;
    /**
     * Creates new form fromCompraPassagem
     * @param parametro
     */
    public formCompraPassagem(Object obj, int indiceLinha) {
        initComponents();
        txtVlPassagem.setEditable(false);
        formUtils = new FormUtils();
        chkMaiorQue.setEnabled(false);
        model = (VooTableModel) obj;
        voo = model.getVoo(indiceLinha);
        try {
            formUtils.carregaComboBoxPoltrona(cmbPoltrona, voo);
        } catch (SQLException ex) {
            Logger.getLogger(formCompraPassagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private formCompraPassagem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPoltrona = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        chkBagagem = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        chkMaiorQue = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtVlPassagem = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Poltrona:");

        cmbPoltrona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Bagagem:");

        chkBagagem.setText("Sim");
        chkBagagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkBagagemMouseClicked(evt);
            }
        });

        jLabel3.setText("Peso maior que 30KG?");

        chkMaiorQue.setText("Sim");
        chkMaiorQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMaiorQueActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor Passagem:");

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(chkBagagem))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMaiorQue)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtVlPassagem, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComprar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPoltrona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBagagem)
                    .addComponent(chkMaiorQue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVlPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprar)
                    .addComponent(btnCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBagagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkBagagemMouseClicked
        //Valor da Bagagem = 50
        //Atualiza o valor do campo valor passagem
        if(!chkBagagem.isSelected()){
            chkMaiorQue.setEnabled(false);
            chkMaiorQue.setSelected(false);
            txtVlPassagem.setText(String.valueOf(voo.getVlVoo()));
        }else{
            chkMaiorQue.setEnabled(true);
            txtVlPassagem.setText(String.valueOf(voo.getVlVoo() + 50));
        }
        
    }//GEN-LAST:event_chkBagagemMouseClicked

    private void chkMaiorQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMaiorQueActionPerformed
        // Valor da Bagagem = 50 + 30 * 5,23 acima de 30 KG
        //Atualiza o valor do campo valor passagem
        if(chkMaiorQue.isSelected()){
            txtVlPassagem.setText(String.valueOf(voo.getVlVoo() + 50 + (30 * 5.23)));
        }else{
            txtVlPassagem.setText(String.valueOf(voo.getVlVoo() + 50));
        }
    }//GEN-LAST:event_chkMaiorQueActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        try {
                          
            Passagem passagem = new Passagem(GerarDados.gerarLocalizador(voo.getVooTag()).toUpperCase());
            VooPoltrona poltrona = new VooPoltrona();
            passagem.setCpfPassageiro(FormUtils.cliente);
            passagem.setPassBagagem(Integer.parseInt(txtVlPassagem.getText()));
            
            try {
                Facade.getInstance().insertDataDB("insert", passagem);
                JOptionPane.showMessageDialog(this, "Seu localizador é: " + passagem.getPassLocalizador().toUpperCase(), "Aviso",JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException e) {
                System.out.println(e.getMessage());
            }
            
            try{
                poltrona.setLocalizador(passagem);
                poltrona.setStatus(new Status(2));
                poltrona.setVooTag(voo);
                poltrona.setPoltrona(Integer.parseInt(cmbPoltrona.getSelectedItem().toString()));
                Facade.getInstance().insertDataDB("insert", poltrona);
            }catch (Exception ex){
                System.out.println(ex.getMessage());
            }
            
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(formCompraPassagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCompraPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCompraPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCompraPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCompraPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCompraPassagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JCheckBox chkBagagem;
    private javax.swing.JCheckBox chkMaiorQue;
    private javax.swing.JComboBox<String> cmbPoltrona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtVlPassagem;
    // End of variables declaration//GEN-END:variables
}
